name: Submission

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ vars.NAME }}
      EMAIL: ${{ vars.EMAIL }}
      RESUME_LINK: ${{ vars.RESUME_LINK }}
      REPOSITORY_LINK: ${{ vars.REPOSITORY_LINK }}
      ACTION_RUN_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run submission script
        run: python submit_application.py
